apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: agent-api
  namespace: default
spec:
  serviceRef:
    name: agent-api
    port: 8080
  targetGroupARN: REPLACE_WITH_ALB_TARGET_GROUP_ARN
